name: whoisit
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  freezed_annotation: ^2.2.0
  intl: ^0.18.1
  riverpod_annotation: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.0
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/faces/humans1/
